# Cloud Build Configuration for MAS Student Services Platform
# This file is used for CI/CD deployment to Google Cloud Run or Railway

steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/mas-app:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/mas-app:latest'
      - '.'
    id: 'build-image'

  # Step 2: Push Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/mas-app:$COMMIT_SHA'
    id: 'push-image'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'mas-app'
      - '--image'
      - 'gcr.io/$PROJECT_ID/mas-app:$COMMIT_SHA'
      - '--region'
      - 'me-central1'  # Doha, Qatar region for Middle East
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'  # Change to 1 to avoid cold starts
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'ASPNETCORE_ENVIRONMENT=Production'
    id: 'deploy-cloud-run'

# Images to be pushed to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/mas-app:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/mas-app:latest'

# Options
options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

# Timeout for entire build process
timeout: '1200s'
