// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mas.Data;

#nullable disable

namespace mas.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260119195002_AddCreatedAtToSiteSettings")]
    partial class AddCreatedAtToSiteSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("mas.Models.AboutContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MainContentAr")
                        .HasColumnType("TEXT");

                    b.Property<string>("MainContentEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("MainImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("MissionContentAr")
                        .HasColumnType("TEXT");

                    b.Property<string>("MissionContentEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("MissionIcon")
                        .HasColumnType("TEXT");

                    b.Property<string>("MissionTitleAr")
                        .HasColumnType("TEXT");

                    b.Property<string>("MissionTitleEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubtitleAr")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubtitleEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamSectionDescriptionAr")
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamSectionDescriptionEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamSectionTitleAr")
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamSectionTitleEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleAr")
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleEn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value1DescriptionAr")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value1DescriptionEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value1Icon")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value1TitleAr")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value1TitleEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value2DescriptionAr")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value2DescriptionEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value2Icon")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value2TitleAr")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value2TitleEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value3DescriptionAr")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value3DescriptionEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value3Icon")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value3TitleAr")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value3TitleEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValuesTitleAr")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValuesTitleEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("VisionContentAr")
                        .HasColumnType("TEXT");

                    b.Property<string>("VisionContentEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("VisionIcon")
                        .HasColumnType("TEXT");

                    b.Property<string>("VisionTitleAr")
                        .HasColumnType("TEXT");

                    b.Property<string>("VisionTitleEn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AboutContents");
                });

            modelBuilder.Entity("mas.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AcceptsMarketing")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("mas.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionAr")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconClass")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("mas.Models.ContactContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddressAr")
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("FormDescriptionAr")
                        .HasColumnType("TEXT");

                    b.Property<string>("FormDescriptionEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("FormTitleAr")
                        .HasColumnType("TEXT");

                    b.Property<string>("FormTitleEn")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("TEXT");

                    b.Property<string>("MapEmbedUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("PageSubtitleAr")
                        .HasColumnType("TEXT");

                    b.Property<string>("PageSubtitleEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("PageTitleAr")
                        .HasColumnType("TEXT");

                    b.Property<string>("PageTitleEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("SuccessMessageAr")
                        .HasColumnType("TEXT");

                    b.Property<string>("SuccessMessageEn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WhatsAppNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkingHoursAr")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkingHoursEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkingHoursTitleAr")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkingHoursTitleEn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ContactContents");
                });

            modelBuilder.Entity("mas.Models.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("mas.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SubscribedToMarketing")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WhatsAppNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("mas.Models.FAQ", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnswerAr")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnswerEn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QuestionAr")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestionEn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FAQs");
                });

            modelBuilder.Entity("mas.Models.HomeContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AboutImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("AboutSectionContentAr")
                        .HasColumnType("TEXT");

                    b.Property<string>("AboutSectionContentEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("AboutSectionTitleAr")
                        .HasColumnType("TEXT");

                    b.Property<string>("AboutSectionTitleEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Feature1DescriptionAr")
                        .HasColumnType("TEXT");

                    b.Property<string>("Feature1DescriptionEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Feature1Icon")
                        .HasColumnType("TEXT");

                    b.Property<string>("Feature1TitleAr")
                        .HasColumnType("TEXT");

                    b.Property<string>("Feature1TitleEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Feature2DescriptionAr")
                        .HasColumnType("TEXT");

                    b.Property<string>("Feature2DescriptionEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Feature2Icon")
                        .HasColumnType("TEXT");

                    b.Property<string>("Feature2TitleAr")
                        .HasColumnType("TEXT");

                    b.Property<string>("Feature2TitleEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Feature3DescriptionAr")
                        .HasColumnType("TEXT");

                    b.Property<string>("Feature3DescriptionEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Feature3Icon")
                        .HasColumnType("TEXT");

                    b.Property<string>("Feature3TitleAr")
                        .HasColumnType("TEXT");

                    b.Property<string>("Feature3TitleEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Feature4DescriptionAr")
                        .HasColumnType("TEXT");

                    b.Property<string>("Feature4DescriptionEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Feature4Icon")
                        .HasColumnType("TEXT");

                    b.Property<string>("Feature4TitleAr")
                        .HasColumnType("TEXT");

                    b.Property<string>("Feature4TitleEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeaturesSectionTitleAr")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeaturesSectionTitleEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeroButtonLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeroButtonTextAr")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeroButtonTextEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeroImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeroSubtitleAr")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeroSubtitleEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeroTitleAr")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeroTitleEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServicesSectionSubtitleAr")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServicesSectionSubtitleEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServicesSectionTitleAr")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServicesSectionTitleEn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HomeContents");
                });

            modelBuilder.Entity("mas.Models.MarketingCampaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SentCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MarketingCampaigns");
                });

            modelBuilder.Entity("mas.Models.Page", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentAr")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentEn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FeaturedImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconClass")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetaDescriptionAr")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetaDescriptionEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetaKeywords")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ShowInMenu")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleEn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pages");
                });

            modelBuilder.Entity("mas.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DeliveryTimeDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescriptionAr")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionEn")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("DiscountPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailContact")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalImagePath")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WhatsAppNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsFeatured");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("mas.Models.SiteSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AboutAr")
                        .HasColumnType("TEXT");

                    b.Property<string>("AboutEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnableDarkMode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableTestimonials")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableWhatsAppButton")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FacebookUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("FaviconPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("InstagramUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("LinkedInUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoPath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("MaintenanceMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetaDescriptionAr")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetaDescriptionEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetaKeywords")
                        .HasColumnType("TEXT");

                    b.Property<string>("MissionAr")
                        .HasColumnType("TEXT");

                    b.Property<string>("MissionEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryColor")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecondaryColor")
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteNameEn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TwitterUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VisionAr")
                        .HasColumnType("TEXT");

                    b.Property<string>("VisionEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("WhatsAppNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SiteSettings");
                });

            modelBuilder.Entity("mas.Models.Testimonial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerImage")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerTitle")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TestimonialText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Testimonials");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("mas.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("mas.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mas.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("mas.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("mas.Models.Product", b =>
                {
                    b.HasOne("mas.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("mas.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
